### ISSUE TITLE
Bug Report # Error on line 4

### ISSUE THREAD

**Issue by EnchaJini** [lownignitus/SkillHelper#1]
(loaded into the game after the recent addon update)

Date: 2020-05-04 11:43:08
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SkillHelper\SkillHelper.lua line 4:
   unexpected symbol near '<'
Debug:
   [string "=[C]"]: ?

**Comment by lownignitus** [comment]
Seems when I mergerd my local repo with github there was a hickup that added the changes to the push. Removed, fixed. Update being pushed.
