### ISSUE TITLE
Shadowlands (9.0.1) issues with Setting BackDrop

### ISSUE THREAD

**Issue by karpana** [lownignitus/SkillHelper#2]
Hi There,

I know that shadowlands seems to have caused issues to many addons as a result of some deprecated API functions.
In Skillhelper, one of these functions is setBackdrop.

I don't know what the "correct" solution is to fix this, as I'm not great at debugging LUA, but as a quick and dirty hack, I commented out the following lines in SkillHelper.lua
```
line 236:  shFrame:SetBackdrop(shFrameBG)
line 422:  shMiscFrame:SetBackdrop(shOptionsBG
line 508:  shScaleFrame:SetBackdrop(shOptionsBG)
line 544:  shAlphaFrame:SetBackdrop(shOptionsBG)
line 646:  bar:SetBackdrop(shBarBG)
line 647:  bar:SetBackdropColor(shSettings.colors.baser, shSettings.colors.baseg, shSettings.colors.baseb, shSettings.colors.half)
```

these 6 changes allow the addon to load, although not quite as pretty as it was during 8.3

Hopefully this will help somebody else who is grinding reputations while the addon developer figures out the best plan of attack to correct this properly.

Cheers,
Karpana

**Comment by lownignitus** [comment]
yeah ive been digging into things, as well as trying to help guild members with game changes, and figure out what am doing in WoW right now.

Also put out my shoulder a week ago, so not been spending as much time on things as I normally do with a major patch sadly. 

I hope to figure out a proper fix in time though

**Comment by lownignitus** [comment]
so leaving this here as a bit of a note on how Backdrop has been changed in 9.0:

[https://us.forums.blizzard.com/en/wow/t/addons-now-usable-in-shadowlands-beta/586355/16](url)

**Comment by lownignitus** [comment]
also:

https://www.wowinterface.com/forums/showpost.php?p=336419&postcount=8

**Comment by karpana** [comment]
For those that are inclined to edit the LUA file... my "hack" will get the addon working... but there's "air gaps" around all frame from where a "background" should be.  It's not elegant but it will work until a more robust (and pretty solution can be figured out).

Thank you @lownignitus for your time, effort and patience with us as we're all adapting to the new pre-patch.
Take care of you.  We'll be here when you're ready and able to take a more solid look at the code. 

:-)  Cheers
Karpana @ Arygos [US]

**Comment by karpana** [comment]
@lownignitus 

I figured I would provide you with a link to another addon that was misbehaving for the same "setBackdrop" reason and has a reasonably quick fix.  I recognize that their addon uses XML to define the frame, and yours uses LUA, but maybe there's a parallel between the two that might provide some direction/guidance/clue to help find a quick solution.
https://www.curseforge.com/wow/addons/minimap-button-frame?comment=1643

Cheers,
Karpana @ Arygos [US]

**Comment by karpana** [comment]
Poking around with another addon that provided a detailed fix for their addon... and I managed to get Skill Helper working correctly (as far as I can tell).

**EDIT**:  _The only thing that doesn't seem to work is pressing the fishing button no longer casts..._

Change Line 233 to this:
`	shFrame = CF("Frame", "shFrame", UIParent,"BackdropTemplate")`

Change line 420 to this:
`	local shMiscFrame = CF("Frame", SHMiscFrame, shOptions,"BackdropTemplate")`

change line 506 to this:
`	local shScaleFrame = CF("Frame", "SHScaleFrame", shOptions,"BackdropTemplate")`

change line 542 to this:
`	local shAlphaFrame = CF("Frame", "SHAlphaFrame", shOptions,"BackdropTemplate")`

change line 642 to this:
`		bar = CF("StatusBar", nil, shBarFrame,"BackdropTemplate")`

**Comment by lownignitus** [comment]
I was just working on this tonight and saw you made a replay, thie was basically what I was going to do.

**Comment by lownignitus** [comment]
I do think Ill alkso have to look up library files to add that are 9.0 ready, but will have to see.

**Comment by karpana** [comment]
I wanted to share the the fishing button seems to be working fine.
(I must have had another addon clashing with it)

All in all the 5 lines changes I made above seem to have the whole addon working properly (at least as far as I can tell)

**Comment by lownignitus** [comment]
I found 1 lib that needs updated, otherwise all is good. 

And yeah those are only lines I can see that needed swapped to the new frame system. Im just dragging ass it seems. 

Thanks for the help. Ill be pushing update in a bit and credit you for help in the notes.

**Comment by lownignitus** [comment]
Looking like is back to visually looking the same, no more library errors being thrown, so Im gonna close this unless something else happens.
